indicators:
  #Question 1a
  #NEW CLIENT
  - key: "fp-1a-nc-30-34"
    grouping: "FP"
    description: "Number of new male clients from 30-34 years counseled on family planning services age"
    indicatorQuery: "SELECT count(DISTINCT efc.entity_id) as count
                     FROM ec_fp_counseling efc
                     INNER JOIN ec_family_member efm ON efm.base_entity_id = efc.entity_id
                     INNER JOIN ec_family_planning efl ON efc.entity_id = efl.base_entity_id
                     WHERE 30 <= (date('Now') - date(efm.dob))  AND (date('Now')-date(efm.dob))<= 35
                     AND (efm.gender='Male')
                     AND (efl.client_used_fp_before = 'yes')
                     AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                     date(substr(strftime('%Y-%m-%d', datetime(efc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                     '-' || substr(strftime('%Y-%m-%d', datetime(efc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  