indicators:
  - key: "fp-1a-nc-10-14"
    grouping: "FP"
    description: "Test"
    indicatorQuery: " SELECT count(DISTINCT efp.base_entity_id) as count
                      FROM ec_family_planning efp
                               INNER JOIN ec_family_member fm on fm.base_entity_id = efp.base_entity_id
                               INNER JOIN ec_anc_followup eaf on fm.base_entity_id = eaf.entity_id
                      WHERE CAST(eaf.gest_age as INT) < 12 AND eaf.visit_number = 1
                        AND is_transfer_in IS NULL
                        AND (date(fm.dob, '+10 yefps') <= date('now'))
                        AND (date(fm.dob, '+15 yefps') > date('now'))
                        AND date(substr(strftime('%Y-%m-%d', datetime(efp.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                          '-' ||
                          substr(strftime('%Y-%m-%d', datetime(efp.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||
                          '-' || '01') =
                          date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01'))";
  
  